//! Differential test against the TS implementation of `keys.ts`.
//!
//! `tests/fixtures/keys-oracle.json` holds the behaviour of
//! `packages/tui/src/keys.ts` for 1611 input sequences × 637 key identifiers,
//! recorded for both Kitty protocol states. Generated by
//! `tools/gen-keys-oracle.mjs`.

use std::sync::{Mutex, MutexGuard, OnceLock};

use notagent_tui::keys::{
    decode_kitty_printable, decode_printable_key, is_key_release, is_key_repeat, matches_key,
    parse_key, set_kitty_protocol_active,
};
use serde_json::Value;

fn guard() -> MutexGuard<'static, ()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

fn oracle() -> Value {
    serde_json::from_str(include_str!("fixtures/keys-oracle.json")).expect("fixture is valid JSON")
}

fn check_snapshot(data: &Value, section: &str, key_ids: &[String], mismatches: &mut Vec<String>) {
    for case in data[section].as_array().expect("section array") {
        let input = case["input"].as_str().expect("input");

        let expected_parse = case["parseKey"].as_str();
        let actual_parse = parse_key(input);
        if actual_parse.as_deref() != expected_parse {
            mismatches.push(format!(
                "{section} parse_key({input:?}): TS {expected_parse:?} vs Rust {actual_parse:?}"
            ));
        }

        for (name, expected, actual) in [
            (
                "is_key_release",
                case["isKeyRelease"].as_bool().expect("bool"),
                is_key_release(input),
            ),
            (
                "is_key_repeat",
                case["isKeyRepeat"].as_bool().expect("bool"),
                is_key_repeat(input),
            ),
        ] {
            if expected != actual {
                mismatches.push(format!(
                    "{section} {name}({input:?}): TS {expected} vs Rust {actual}"
                ));
            }
        }

        for (name, expected, actual) in [
            (
                "decode_kitty_printable",
                case["decodeKittyPrintable"].as_str(),
                decode_kitty_printable(input),
            ),
            (
                "decode_printable_key",
                case["decodePrintableKey"].as_str(),
                decode_printable_key(input),
            ),
        ] {
            if actual.as_deref() != expected {
                mismatches.push(format!(
                    "{section} {name}({input:?}): TS {expected:?} vs Rust {actual:?}"
                ));
            }
        }

        let expected_matches: Vec<&str> = case["matches"]
            .as_array()
            .expect("matches")
            .iter()
            .map(|v| v.as_str().expect("key id"))
            .collect();
        for key_id in key_ids {
            let expected = expected_matches.contains(&key_id.as_str());
            let actual = matches_key(input, key_id);
            if expected != actual {
                mismatches.push(format!(
                    "{section} matches_key({input:?}, {key_id:?}): TS {expected} vs Rust {actual}"
                ));
            }
        }
    }
}

#[test]
fn keys_behaviour_matches_typescript() {
    let _guard = guard();
    // The fixture was recorded without WT_SESSION (Windows Terminal heuristic).
    let previous = std::env::var("WT_SESSION").ok();
    // SAFETY: tests in this binary are serialized through `guard()`.
    unsafe { std::env::remove_var("WT_SESSION") };

    let data = oracle();
    let key_ids: Vec<String> = data["keyIds"]
        .as_array()
        .expect("keyIds")
        .iter()
        .map(|v| v.as_str().expect("key id").to_string())
        .collect();

    let mut mismatches = Vec::new();

    set_kitty_protocol_active(false);
    check_snapshot(&data, "legacy", &key_ids, &mut mismatches);
    set_kitty_protocol_active(true);
    check_snapshot(&data, "kitty", &key_ids, &mut mismatches);
    set_kitty_protocol_active(false);

    if let Some(previous) = previous {
        // SAFETY: see above.
        unsafe { std::env::set_var("WT_SESSION", previous) };
    }

    assert!(
        mismatches.is_empty(),
        "{} deviations:\n{}",
        mismatches.len(),
        mismatches
            .iter()
            .take(25)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
