//! Differential test against the TS implementation of `stdin-buffer.ts`.
//!
//! `tests/fixtures/stdin-buffer-oracle.json` records the synchronous event
//! stream of the TS buffer for realistic input streams cut into every plausible
//! chunking — the part of the state machine that fragmentation can break.
//! Generated by `tools/gen-stdin-buffer-oracle.mjs`.

use notagent_tui::stdin_buffer::{StdinBuffer, StdinBufferOptions, StdinEvent};
use serde_json::Value;

#[test]
fn stdin_buffer_matches_typescript_across_chunk_boundaries() {
    let data: Value = serde_json::from_str(include_str!("fixtures/stdin-buffer-oracle.json"))
        .expect("fixture is valid JSON");

    let mut mismatches = Vec::new();
    let cases = data["cases"].as_array().expect("cases");
    for case in cases {
        let chunks: Vec<&str> = case["chunks"]
            .as_array()
            .expect("chunks")
            .iter()
            .map(|c| c.as_str().expect("chunk"))
            .collect();

        let mut buffer = StdinBuffer::new(StdinBufferOptions {
            timeout: Some(10),
            escape_timeout: None,
        });
        let mut actual = Vec::new();
        for chunk in &chunks {
            actual.extend(buffer.process(chunk));
        }

        let expected: Vec<StdinEvent> = case["events"]
            .as_array()
            .expect("events")
            .iter()
            .map(|event| {
                let payload = event["data"].as_str().expect("data").to_string();
                match event["type"].as_str().expect("type") {
                    "paste" => StdinEvent::Paste(payload),
                    _ => StdinEvent::Data(payload),
                }
            })
            .collect();

        if actual != expected {
            mismatches.push(format!(
                "{chunks:?}:\n  TS   {expected:?}\n  Rust {actual:?}"
            ));
        }

        let expected_remainder = case["remainder"].as_str().expect("remainder");
        if buffer.get_buffer() != expected_remainder {
            mismatches.push(format!(
                "{chunks:?} remainder: TS {expected_remainder:?} vs Rust {:?}",
                buffer.get_buffer()
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} cases deviate:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
