//! 1:1 port of `packages/coding-agent/src/modes/interactive/components/diff.ts` (147 LOC).
//!
//! The `diff` npm package (jsdiff 8.0.4) is not available in Rust. The master
//! plan substitutes `similar` for unified patches; `diffWords` has no equivalent
//! there — its tokenisation, its whitespace-insensitive comparison and its
//! whitespace post-processing decide which spans get inverse-highlighted, and
//! `similar` groups edits differently. [`word_diff`] therefore ports jsdiff's
//! word diff itself (`libesm/diff/base.js`, `libesm/diff/word.js` and the parts
//! of `libesm/util/string.js` they use) for the option set `renderDiff` calls it
//! with: no segmenter, no `ignoreCase`, no comparator, no `oneChangePerToken`,
//! no edit-length or time limit. `tests/diff_words_oracle.rs` compares the
//! result with the real jsdiff output for a corpus generated by
//! `tools/gen-diff-words-oracle.mjs`.

use crate::modes::interactive::theme::theme::{
    BlockStyle, ThemeBg, ThemeColor, block_style, theme,
};

pub mod word_diff;

use crate::modes::interactive::theme::theme::ansi_rgb;

/// Linear blend from `base` toward `toward` by `t` (reference `blend_rgb`).
fn blend_rgb(base: (u8, u8, u8), toward: (u8, u8, u8), t: f32) -> (u8, u8, u8) {
    let mix = |a: u8, b: u8| -> u8 { (f32::from(a) + (f32::from(b) - f32::from(a)) * t) as u8 };
    (
        mix(base.0, toward.0),
        mix(base.1, toward.1),
        mix(base.2, toward.2),
    )
}

/// The badge style's diff-line background: the block wash pulled toward the
/// diff accent — a notch for whole lines, strongly for the changed tokens of
/// a single-line modification. Falls back to the plain wash (line) or an
/// empty string (emphasis) when the theme is not truecolor (reference
/// `diff_wash`).
fn diff_wash(added: bool, emphasis: bool) -> String {
    let theme = theme();
    let (bg_token, fg_token) = if added {
        (ThemeBg::ToolSuccessBg, ThemeColor::ToolDiffAdded)
    } else {
        (ThemeBg::ToolErrorBg, ThemeColor::ToolDiffRemoved)
    };
    let base = ansi_rgb(theme.get_bg_ansi(bg_token));
    let accent = ansi_rgb(theme.get_fg_ansi(fg_token));
    match (base, accent) {
        (Some(base), Some(accent)) => {
            let t = if emphasis { 0.45 } else { 0.18 };
            let (r, g, b) = blend_rgb(base, accent, t);
            format!("\x1b[48;2;{r};{g};{b}m")
        }
        _ if emphasis => String::new(),
        _ => theme.get_bg_ansi(bg_token).to_string(),
    }
}

/// The open/close pair wrapped around changed tokens of a modified line: the
/// emphasis wash restoring to the line's own wash in the badge style, plain
/// inverse in the standard style (and as the non-truecolor fallback).
fn emphasis_style(added: bool) -> (String, String) {
    if block_style() == BlockStyle::Badge {
        let emphasis = diff_wash(added, true);
        if !emphasis.is_empty() {
            return (emphasis, diff_wash(added, false));
        }
    }
    ("\x1b[7m".to_string(), "\x1b[27m".to_string())
}

/// Parsed shape of a diff line.
struct ParsedDiffLine<'a> {
    prefix: char,
    line_num: &'a str,
    content: &'a str,
}

/// Parse diff line to extract prefix, line number, and content.
/// Format: `"+123 content"` or `"-123 content"` or `" 123 content"` or `"     ..."`
///
/// Port of `/^([+-\s])(\s*\d*)\s(.*)$/`. `.` does not match line terminators,
/// so a line containing one never matches.
fn parse_diff_line(line: &str) -> Option<ParsedDiffLine<'_>> {
    let prefix = line.chars().next()?;
    if prefix != '+' && prefix != '-' && !word_diff::is_js_whitespace(prefix) {
        return None;
    }
    let rest = &line[prefix.len_utf8()..];
    let chars: Vec<(usize, char)> = rest.char_indices().collect();

    // `\s*` is greedy: start with the longest run of whitespace and shorten it
    // the way the regex engine backtracks.
    let mut max_whitespace = 0;
    while max_whitespace < chars.len() && word_diff::is_js_whitespace(chars[max_whitespace].1) {
        max_whitespace += 1;
    }

    for whitespace_len in (0..=max_whitespace).rev() {
        // `\d*` is greedy as well.
        let mut max_digits = 0;
        while whitespace_len + max_digits < chars.len()
            && chars[whitespace_len + max_digits].1.is_ascii_digit()
        {
            max_digits += 1;
        }
        for digits_len in (0..=max_digits).rev() {
            let separator_index = whitespace_len + digits_len;
            if separator_index >= chars.len() {
                continue;
            }
            let (separator_offset, separator) = chars[separator_index];
            if !word_diff::is_js_whitespace(separator) {
                continue;
            }
            let content = &rest[separator_offset + separator.len_utf8()..];
            // `.` never matches a line terminator and `$` anchors at the end,
            // so a content group containing one makes the match fail.
            if content.contains(['\n', '\r', '\u{2028}', '\u{2029}']) {
                continue;
            }
            return Some(ParsedDiffLine {
                prefix,
                line_num: &rest[..separator_offset],
                content,
            });
        }
    }
    None
}

/// Replace tabs with spaces for consistent rendering.
fn replace_tabs(text: &str) -> String {
    text.replace('\t', "   ")
}

/// Compute word-level diff and render with inverse on changed parts.
/// Uses diffWords which groups whitespace with adjacent words for cleaner highlighting.
/// Strips leading whitespace from inverse to avoid highlighting indentation.
fn render_intra_line_diff(old_content: &str, new_content: &str) -> (String, String) {
    let word_diff = word_diff::diff_words(old_content, new_content);

    let mut removed_line = String::new();
    let mut added_line = String::new();
    let mut is_first_removed = true;
    let mut is_first_added = true;

    // The changed tokens read as inverse in the standard style, and as the
    // stronger emphasis wash restoring to the line's own wash in the badge
    // style (reference `washed_diff_line`).
    let (removed_open, removed_close) = emphasis_style(false);
    let (added_open, added_close) = emphasis_style(true);
    for part in &word_diff {
        if part.removed {
            let mut value = part.value.as_str();
            // Strip leading whitespace from the first removed part
            if is_first_removed {
                let leading_ws = word_diff::leading_ws(value);
                value = &value[leading_ws.len()..];
                removed_line.push_str(leading_ws);
                is_first_removed = false;
            }
            if !value.is_empty() {
                removed_line.push_str(&format!("{removed_open}{value}{removed_close}"));
            }
        } else if part.added {
            let mut value = part.value.as_str();
            // Strip leading whitespace from the first added part
            if is_first_added {
                let leading_ws = word_diff::leading_ws(value);
                value = &value[leading_ws.len()..];
                added_line.push_str(leading_ws);
                is_first_added = false;
            }
            if !value.is_empty() {
                added_line.push_str(&format!("{added_open}{value}{added_close}"));
            }
        } else {
            removed_line.push_str(&part.value);
            added_line.push_str(&part.value);
        }
    }

    (removed_line, added_line)
}

/// Options of [`render_diff`].
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RenderDiffOptions {
    /// File path (unused, kept for API compatibility)
    pub file_path: Option<String>,
}

/// One removed/added diff row. The standard style colours the whole line in
/// the diff foreground; the badge style washes it with the blended block
/// background, keeps the content in the terminal's own text colour and closes
/// with a full reset (reference `washed_diff_line`).
fn diff_line(added: bool, num: &str, content: &str) -> String {
    let theme = theme();
    let (kind, color) = if added {
        ('+', ThemeColor::ToolDiffAdded)
    } else {
        ('-', ThemeColor::ToolDiffRemoved)
    };
    if block_style() == BlockStyle::Badge {
        format!(
            "{}{} {content}\x1b[0m",
            diff_wash(added, false),
            theme.fg(color, &format!("{kind}{num}")),
        )
    } else {
        theme.fg(color, &format!("{kind}{num} {content}"))
    }
}

/// Render a diff string with colored lines and intra-line change highlighting.
/// - Context lines: dim/gray
/// - Removed lines: red, with inverse on changed tokens
/// - Added lines: green, with inverse on changed tokens
pub fn render_diff(diff_text: &str, _options: &RenderDiffOptions) -> String {
    let lines: Vec<&str> = diff_text.split('\n').collect();
    let mut result: Vec<String> = Vec::new();
    let theme = theme();

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let Some(parsed) = parse_diff_line(line) else {
            result.push(theme.fg(ThemeColor::ToolDiffContext, line));
            i += 1;
            continue;
        };

        if parsed.prefix == '-' {
            // Collect consecutive removed lines
            let mut removed_lines: Vec<(String, String)> = Vec::new();
            while i < lines.len() {
                let Some(parsed) = parse_diff_line(lines[i]) else {
                    break;
                };
                if parsed.prefix != '-' {
                    break;
                }
                removed_lines.push((parsed.line_num.to_string(), parsed.content.to_string()));
                i += 1;
            }

            // Collect consecutive added lines
            let mut added_lines: Vec<(String, String)> = Vec::new();
            while i < lines.len() {
                let Some(parsed) = parse_diff_line(lines[i]) else {
                    break;
                };
                if parsed.prefix != '+' {
                    break;
                }
                added_lines.push((parsed.line_num.to_string(), parsed.content.to_string()));
                i += 1;
            }

            // Only do intra-line diffing when there's exactly one removed and one added line
            // (indicating a single line modification). Otherwise, show lines as-is.
            if removed_lines.len() == 1 && added_lines.len() == 1 {
                let removed = &removed_lines[0];
                let added = &added_lines[0];

                let (removed_line, added_line) =
                    render_intra_line_diff(&replace_tabs(&removed.1), &replace_tabs(&added.1));

                result.push(diff_line(false, &removed.0, &removed_line));
                result.push(diff_line(true, &added.0, &added_line));
            } else {
                // Show all removed lines first, then all added lines
                for removed in &removed_lines {
                    result.push(diff_line(false, &removed.0, &replace_tabs(&removed.1)));
                }
                for added in &added_lines {
                    result.push(diff_line(true, &added.0, &replace_tabs(&added.1)));
                }
            }
        } else if parsed.prefix == '+' {
            // Standalone added line
            result.push(diff_line(
                true,
                parsed.line_num,
                &replace_tabs(parsed.content),
            ));
            i += 1;
        } else {
            // Context line
            result.push(theme.fg(
                ThemeColor::ToolDiffContext,
                &format!(" {} {}", parsed.line_num, replace_tabs(parsed.content)),
            ));
            i += 1;
        }
    }

    result.join("\n")
}
